#config_version=6

show_player:
    mode_attract_started:
        glass_wave_reveal_show:
            priority: 200
            loops: 3
            events_when_completed: start_rainbow_show
        attract_loop_show:
            priority: 300
            loops: -1
    mode_attract_stopping:
        attract_loop_show:
            action: stop
        glass_wave_reveal_show:
            action: stop
        cabinet_mini_rainbow_show:
            action: stop
    start_rainbow_show:
        cabinet_mini_rainbow_show:
            loops: 2
            events_when_completed: start_wave_show
    start_wave_show:
        glass_wave_reveal_show:
            loops: 3
            events_when_completed: start_rainbow_show

slides:
    dspc_logo_slide:
        widgets:
            type: video
            video: dspc_animation
