#config_version=6


show_player:
    start_attract_shows:
#        glass_wave_reveal_show:
#            loops: 3
#            speed: 1
#            events_when_completed: start_rainbow_show
#            priority: 1
        attract_loop_show:
            loops: 0
            events_when_stopped: restart_attract_loop
        attract_backbox_show:
            loops: -1
            priority: 3
            speed: 1
    end_attract_loop:
        attract_loop_show:
            action: stop
    restart_attract_loop:
        attract_loop_show:
            loops: 0
    start_PF_attract_show:
        glowfly_attract_loop_show:
            loops: 0
    mode_attract_stopping:
        attract_loop_show:
            action: stop
        glass_wave_reveal_show:
            action: stop
        cabinet_mini_rainbow_show:
            action: stop
#    start_rainbow_show:
#        cabinet_mini_rainbow_show:
#            loops: 2
#            events_when_completed: start_wave_show
#    start_wave_show:
#        glass_wave_reveal_show:
#            loops: 3
#            events_when_completed: start_rainbow_show
#            speed: 1
    left_flips_full:
        glass_wave_reveal_show:
            action: stop
        cabinet_mini_rainbow_show:
            action: stop
    right_flips_full:
        glass_wave_reveal_show:
            action: stop
        cabinet_mini_rainbow_show:
            action: stop

light_player:
    mode_attract_started:
        bbox: "ffffff"
    
slides:
    dspc_logo_slide:
        widgets:
            - type: video
              video: dspc_animation
              width: 782
              height: 440
              x: left+241
            - type: text
              text: Deathsave Pinball Cult
              x: middle+300
              y: center+70
              color: white
              font_size: 90
            - type: text
              text: Presents
              x: middle+300
              y: center-70
              color: white
              font_size: 90
    glowfly_title_slide:
        widgets:
            type: image
            image: glowfly_title
            scale: .9
