#config_version=6
mode:
    start_events: ball_started
    priority: 100

ball_saves:
    ball_start_ball_save:
        active_time: "+5s"
        hurry_up_time: 6s
        timer_start_events: s_shooter_lane_inactive
        auto_launch: true
        balls_to_save: 1

light_player:
    s_shooter_lane_active:
        lamps: off
        cabinet: off

show_player:
    s_shooter_lane_active:
        base_glimmer_show:
            action: stop
    s_shooter_lane_inactive:
        base_glimmer_show:
            loops: -1
            show_tokens:
                color1: "ff0000"
                color2: "110000"


coil_player:
    timer_all_glow_timer_started:
        glow_coil: on
    timer_all_glow_timer_stopped:
        glow_coil: off
    s_shooter_lane_active:
        c_glow_shooter_lane: on
    s_shooter_lane_inactive:
        c_glow_shooter_lane: off


timers:
    all_glow_timer:
        start_value: 4
        end_value: 0
        direction: down
        tick_interval: 1s
        control_events:
            - action: start
              event: playfield_active
            - action: add
              event: playfield_active
              value: 4
            - action: stop
              event: glow_off
