#config_version=6
mode:
    start_events: ball_started
    priority: 100

ball_saves:
    ball_start_ball_save:
        active_time: "+5s"
        hurry_up_time: 6s
        timer_start_events: s_shooter_lane_inactive
        auto_launch: true
        balls_to_save: 1

light_player:
    s_right_flipper_active:
        cabinet: ffffff
    s_left_flipper_active:
        cabinet: "000000"
    s_shooter_lane_inactive:
        blocks: red
        lanes: yellow
        slings: orange
    s_shooter_lane_active:
        blocks: "000000"
        lanes: "000000"
        slings: "000000"
