#config_version=6

virtual_platform_start_active_switches:
    - s_trough1
    - s_trough2
    - s_trough3

keyboard:
    s:
        event: #start game

hardware:
    platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      cabinet_board:
        model: FP-I/O-0024
        order: 1
      1616:
        model: FP-I/O-1616
        order: 2
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  exp:
    boards:
      neuron:
        model: FP-EXP-2000
      playfield:
        model: FP-EXP-0081

light_settings:
    default_fade_ms: 40

lights:
    l_left_sling1:
        number: playfield-2-1
        tags: lamps, gi, slings
    l_left_sling2:
        number: playfield-2-2
        tags: lamps, gi, slings
    l_left_lane1:
        number: playfield-2-3
        tags: lamps, gi, lanes
    l_left_lane2:
        number: playfield-2-4
        tags: lamps, gi, lanes
    l_left_lane_block1:
        number: playfield-2-5
        tags: lamps, blocks, lanes
    l_left_lane_block2:
        number: playfield-2-6
        tags: lamps, blocks, lanes
    l_left_lane_block3:
        number: playfield-2-7
        tags: lamps, blocks, lanes
    l_left_lane_block4:
        number: playfield-2-8
        tags: lamps, blocks, lanes
    l_left_lane_block5:
        number: playfield-2-9
        tags: lamps, blocks, lanes
    l_left_lane_block6:
        number: playfield-2-10
        tags: lamps, blocks, lanes
    l_left_lane_block7:
        number: playfield-2-11
        tags: lamps, blocks, lanes
    l_left_lane_block8:
        number: playfield-2-12
        tags: lamps, blocks, lanes
    l_left_lane_block9:
        number: playfield-2-13
        tags: lamps, blocks, lanes
    l_left_lane_block10:
        number: playfield-2-14
        tags: lamps, blocks, lanes
    l_left_lane_block11:
        number: playfield-2-15
        tags: lamps, blocks, lanes
    l_left_lane_block12:
        number: playfield-2-16
        tags: lamps, blocks, lanes
#right lower
    l_right_sling1:
        number: playfield-3-1
        tags: lamps, gi, slings
    l_right_sling2:
        number: playfield-3-2
        tags: lamps, gi, slings
    l_right_lane1:
        number: playfield-3-3
        tags: lamps, gi, lanes
    l_right_lane2:
        number: playfield-3-4
        tags: lamps, gi, lanes
    l_right_lane_block1:
        number: playfield-3-5
        tags: lamps, blocks, lanes
    l_right_lane_block2:
        number: playfield-3-6
        tags: lamps, blocks, lanes
    l_right_lane_block3:
        number: playfield-3-7
        tags: lamps, blocks, lanes
    l_right_lane_block4:
        number: playfield-3-8
        tags: lamps, blocks, lanes
    l_right_lane_block5:
        number: playfield-3-9
        tags: lamps, blocks, lanes
    l_right_lane_block6:
        number: playfield-3-10
        tags: lamps, blocks, lanes
    l_right_lane_block7:
        number: playfield-3-11
        tags: lamps, blocks, lanes
    l_right_lane_block8:
        number: playfield-3-12
        tags: lamps, blocks, lanes
    l_right_lane_block9:
        number: playfield-3-13
        tags: lamps, blocks, lanes
    l_right_lane_block10:
        number: playfield-3-14
        tags: lamps, blocks, lanes
    l_right_lane_block11:
        number: playfield-3-15
        tags: lamps, blocks, lanes
    l_right_lane_block12:
        number: playfield-3-16
        tags: lamps, blocks, lanes
#apron lights
    l_apron1:
        number: playfield-1-1
        tags: lamps, apron
    l_apron2:
        number: playfield-1-2
        tags: lamps, apron
#other light blocks
    l_upper_center_block1:
        number: playfield-6-1
        tags: lamps, blocks, upper_center_block
    l_upper_left_block1:
        number: playfield-5-1
        tags: lamps, blocks, upper_left_block
    l_upper_right_block1:
        number: playfield-7-1
        tags: lamps, blocks, upper_right_block
    l_loop_core1:
        number: playfield-8-1
        tags: lamps, blocks, loop_core
#cabinet side lights 
    l_l_cab1:
        number: neuron-1-1
        tags: l_cab, cabinet
    l_l_cab2:
        number: neuron-1-2
        tags: l_cab, cabinet
    l_l_cab3:
        number: neuron-1-3
        tags: l_cab, cabinet
    l_l_cab4:
        number: neuron-1-4
        tags: l_cab, cabinet
    l_l_cab5:
        number: neuron-1-5
        tags: l_cab, cabinet
    l_l_cab6:
        number: neuron-1-6
        tags: l_cab, cabinet
    l_l_cab7:
        number: neuron-1-7
        tags: l_cab, cabinet
    l_l_cab8:
        number: neuron-1-8
        tags: l_cab, cabinet
    l_l_cab9:
        number: neuron-1-9
        tags: l_cab, cabinet
    l_l_cab10:
        number: neuron-1-10
        tags: l_cab, cabinet
    l_l_cab11:
        number: neuron-1-11
        tags: l_cab, cabinet
    l_l_cab12:
        number: neuron-1-12
        tags: l_cab, cabinet
    l_l_cab13:
        number: neuron-1-13
        tags: l_cab, cabinet
    l_l_cab14:
        number: neuron-1-14
        tags: l_cab, cabinet
    l_l_cab15:
        number: neuron-1-15
        tags: l_cab, cabinet
    l_l_cab16:
        number: neuron-1-16
        tags: l_cab, cabinet
    l_l_cab17:
        number: neuron-1-17
        tags: l_cab, cabinet
    l_l_cab18:
        number: neuron-1-18
        tags: l_cab, cabinet
    l_l_cab19:
        number: neuron-1-19
        tags: l_cab, cabinet
    l_l_cab20:
        number: neuron-1-20
        tags: l_cab, cabinet
    l_r_cab1:
        number: neuron-2-1
        tags: r_cab, cabinet
    l_r_cab2:
        number: neuron-2-2
        tags: r_cab, cabinet
    l_r_cab3:
        number: neuron-2-3
        tags: r_cab, cabinet
    l_r_cab4:
        number: neuron-2-4
        tags: r_cab, cabinet
    l_r_cab5:
        number: neuron-2-5
        tags: r_cab, cabinet
    l_r_cab6:
        number: neuron-2-6
        tags: r_cab, cabinet
    l_r_cab7:
        number: neuron-2-7
        tags: r_cab, cabinet
    l_r_cab8:
        number: neuron-2-8
        tags: r_cab, cabinet
    l_r_cab9:
        number: neuron-2-9
        tags: r_cab, cabinet
    l_r_cab10:
        number: neuron-2-10
        tags: r_cab, cabinet
    l_r_cab11:
        number: neuron-2-11
        tags: r_cab, cabinet
    l_r_cab12:
        number: neuron-2-12
        tags: r_cab, cabinet
    l_r_cab13:
        number: neuron-2-13
        tags: r_cab, cabinet
    l_r_cab14:
        number: neuron-2-14
        tags: r_cab, cabinet
    l_r_cab15:
        number: neuron-2-15
        tags: r_cab, cabinet
    l_r_cab16:
        number: neuron-2-16
        tags: r_cab, cabinet
    l_r_cab17:
        number: neuron-2-17
        tags: r_cab, cabinet
    l_r_cab18:
        number: neuron-2-18
        tags: r_cab, cabinet
    l_r_cab19:
        number: neuron-2-19
        tags: r_cab, cabinet
    l_r_cab20:
        number: neuron-2-20
        tags: r_cab, cabinet

switches:
    s_left_flipper:
        number: cabinet_board-15
        tags: left_flipper
    s_right_flipper:
        number: cabinet_board-14
        tags: right_flipper
    s_trough_jam:
        number: cabinet_board-1
        type: NC
    s_trough1:
        number: cabinet_board-2
        type: NC
    s_trough2:
        number: cabinet_board-3
        type: NC
    s_trough3:
        number: cabinet_board-4
        type: NC
    s_shooter_lane:
        number: cabinet_board-5
    s_start:
        number: cabinet_board-23
        tags: start
    s_r_outlane:
        number: 1616-1
        tags: playfield_active
    s_left_outlane:
        number: 1616-2
        tags: playfield_active
    s_left_inlane:
        number: 1616-3
        tags: playfield_active
    s_right_inlane:
        number: 1616-4
        tags: playfield_active
    s_left_sling:
        number: 1616-5
    s_right_sling:
        number: 1616-6
    s_left_lock:
        number: 1616-7

coils:
    c_flipper_left_main:
        number: 1616-0
        default_pulse_ms: 20
    c_flipper_left_hold:
        number: 1616-1
        allow_enable: true
    c_flipper_right_main:
        number: 1616-2
        default_pulse_ms: 20
    c_flipper_right_hold:
        number: 1616-3
        allow_enable: true
    c_plunger:
        number: 1616-7
        default_pulse_ms: 18
    c_trough_eject:
        number: 1616-6
        default_pulse_ms: 12
    c_sling_left:
        number: 1616-4
        default_pulse_ms: 8
    c_sling_right:
        number: 1616-5
        default_pulse_ms: 8
    c_gate:
        number: 1616-8
        default_pulse_ms: 8
        default_hold_power: .625
    c_lock_launcher:
        number: 1616-9
        default_pulse_ms: 25

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough_jam
        eject_coil: c_trough_eject
        eject_targets: bd_plunger
        eject_timeouts: 3s
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        debug: true
    bd_plunger:
        ball_switches: s_shooter_lane
        eject_coil: c_plunger
        mechanical_eject: true
        eject_timeouts: 3s
    bd_left_lock:
        ball_switches: s_left_lock
        eject_coil: c_lock_launcher
        eject_timeouts: 3s
        tags: lock, launcher

diverters:
    left_lock_gate:
        activation_coil: c_gate
        type: hold
        activation_time: 3s
        enable_events: ball_started, s_left_lock_inactive
        disable_events: ball_ended, s_left_lock_active
        targets_when_active: bd_left_lock
        targets_when_inactive: playfield
autofire_coils:
    ac_slingshot_left:
        coil: c_sling_left
        switch: s_left_sling
    ac_slingshot_right:
        coil: c_sling_right
        switch: s_right_sling

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger

flippers:
#these flippers are setup for dual-wound coils, computer controlled
#to switch from high power to hold power automatically when the flipper button
#is held down --no end of stroke switch required
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper

displays:
    window:
        width: 1920
        height: 1080

sound_system:
    buffer: 1024
    channels: 1
    enabled: true
    frequency: 44100
    tracks:
        music:
            type: standard
            simultaneous_sounds: 1
            volume: 0.5
        voice:
            type: standard
            simultaneous_sounds: 1
            volume: 0.9
        sfx:
            type: standard
            simultaneous_sounds: 8
            volume: 0.6

machine_vars:
    master_volume:
        initial_value: 0.8

player_vars:
    pop_bumper_hits:
        initial_value: 0

modes:
    - base
    - bonus
    - high_score

slides:
    welcome_slide:
        widgets:
            - type: text
              text: IF YOU SEE THIS, SOMETHING IS WRONG!
              font_size: 50
              color: red
            - type: rectangle
              width: 240
              height: 60
    attract_started:
        widgets:
            - type: image
              image: ADD_ME
    final_score_slide:
        widgets:
            - type: text
              text: FINAL SCORE
              font_size: 42
              color: black
              y: 900
              x: 1120
              anchor_x: left
              anchor_y: top
            - type: image
              image: final_score
    base_slide:
        widgets:
            - type: text
              text: (player1|score)
              number_grouping: true
              min_digits: 2
              font_size: 45
              color: black
              y: 108
              x: 413
              anchor_x: right
              anchor_y: bottom
            - type: text
              text: PLAYER (number)
              y: 365
              x: 20
              font_size: 50
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: BALL (ball)
              y: 295
              x: 20
              anchor_x: left
              anchor_y: bottom
              font_size: 50
            - type: image
              image: base_background1



widget_player:
    player_added{num==2}:
        player2_scoring:
            slide: base_slide
    player_added{num==3}:
        player3_scoring:
            slide: base_slide
    player_added{num==4}:
        player4_scoring:
            slide: base_slide

widgets:
    player2_scoring:
        - type: text
          text: (player2|score)
          number_grouping: true
          min_digits: 2
          font_size: 45
          color: black
          y: 108
          x: 875
          z: 5
          anchor_x: right
          anchor_y: bottom
    player3_scoring:
        - type: text
          text: (player3|score)
          number_grouping: true
          min_digits: 2
          font_size: 45
          color: black
          y: 108
          x: 1335
          z: 5
          anchor_x: right
          anchor_y: bottom
    player4_scoring:
        - type: text
          text: (player4|score)
          number_grouping: true
          min_digits: 2
          font_size: 45
          color: black
          y: 108
          x: 1795
          z: 5
          anchor_x: right
          anchor_y: bottom

widget_styles:
    attract_mode_high_score_display_label:
        font_size: 40
        anchor_x: right
        anchor_y: top
        x: center-110
        bold: true
    attract_mode_high_score_display_name:
        font_size: 40
        anchor_x: right
        anchor_y: top
        x: center+150
    attract_mode_high_score_display_score:
        font_size: 40
        anchor_x: left
        anchor_y: top
        x: center+240
        number_grouping: true
        min_digits: 1
    attract_mode_final_score_display_player_number:
        font_size: 40
        anchor_x: center
        anchor_y: top
        x: center-80
        bold: true
    attract_mode_final_score_display_score:
        font_size: 40
        anchor_x: left
        anchor_y: top
        x: center+60
        number_grouping: true
        min_digits: 1

assets:
    sounds:
        default:
            load: on_demand
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice


slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started
    game_ending:
        final_score_slide:
            expire: 30s
