#config_version=6
##! mode: glow_and_decay

mode:
    start_events: s_shooter_lane_inactive
    stop_events: s_shooter_lane_active
    priority: 250

timers:
    decay:
        start_value: 0
        end_value: 3
        restart_on_complete: true
        start_running: true

variable_player:
    timer_decay_complete{current_player.spark > 0}:
        spark: -1

light_player:
    player_spark{value==20}:
        l_l_cab1: on
        l_l_cab2: on
        l_l_cab3: on
        l_l_cab4: on
        l_l_cab5: on
        l_l_cab6: on
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: on
        l_r_cab2: on
        l_r_cab3: on
        l_r_cab4: on
        l_r_cab5: on
        l_r_cab6: on
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==19}:
        l_l_cab1: off
        l_l_cab2: on
        l_l_cab3: on
        l_l_cab4: on
        l_l_cab5: on
        l_l_cab6: on
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: on
        l_r_cab3: on
        l_r_cab4: on
        l_r_cab5: on
        l_r_cab6: on
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==18}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: on
        l_l_cab4: on
        l_l_cab5: on
        l_l_cab6: on
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: on
        l_r_cab4: on
        l_r_cab5: on
        l_r_cab6: on
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==17}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: on
        l_l_cab5: on
        l_l_cab6: on
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: on
        l_r_cab5: on
        l_r_cab6: on
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==16}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: on
        l_l_cab6: on
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: on
        l_r_cab6: on
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==15}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: on
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: on
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==14}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: on
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: on
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==13}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: on
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: on
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==12}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: on
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: on
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==11}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: on
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: on
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==10}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: on
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: on
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==9}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: on
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: on
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==8}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: on
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: on
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==7}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: on
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: on
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==6}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: on
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: on
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==5}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: off
        l_l_cab16: on
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: off
        l_r_cab16: on
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==4}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: off
        l_l_cab16: off
        l_l_cab17: on
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: off
        l_r_cab16: off
        l_r_cab17: on
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==3}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: off
        l_l_cab16: off
        l_l_cab17: off
        l_l_cab18: on
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: off
        l_r_cab16: off
        l_r_cab17: off
        l_r_cab18: on
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==2}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: off
        l_l_cab16: off
        l_l_cab17: off
        l_l_cab18: off
        l_l_cab19: on
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: off
        l_r_cab16: off
        l_r_cab17: off
        l_r_cab18: off
        l_r_cab19: on
        l_r_cab20: on
    player_spark{value==1}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: off
        l_l_cab16: off
        l_l_cab17: off
        l_l_cab18: off
        l_l_cab19: off
        l_l_cab20: on
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: off
        l_r_cab16: off
        l_r_cab17: off
        l_r_cab18: off
        l_r_cab19: off
        l_r_cab20: on
    player_spark{value==0}:
        l_l_cab1: off
        l_l_cab2: off
        l_l_cab3: off
        l_l_cab4: off
        l_l_cab5: off
        l_l_cab6: off
        l_l_cab7: off
        l_l_cab8: off
        l_l_cab9: off
        l_l_cab10: off
        l_l_cab11: off
        l_l_cab12: off
        l_l_cab13: off
        l_l_cab14: off
        l_l_cab15: off
        l_l_cab16: off
        l_l_cab17: off
        l_l_cab18: off
        l_l_cab19: off
        l_l_cab20: off
        l_r_cab1: off
        l_r_cab2: off
        l_r_cab3: off
        l_r_cab4: off
        l_r_cab5: off
        l_r_cab6: off
        l_r_cab7: off
        l_r_cab8: off
        l_r_cab9: off
        l_r_cab10: off
        l_r_cab11: off
        l_r_cab12: off
        l_r_cab13: off
        l_r_cab14: off
        l_r_cab15: off
        l_r_cab16: off
        l_r_cab17: off
        l_r_cab18: off
        l_r_cab19: off
        l_r_cab20: off
